"""
Pseudo-label Loader — YOLO ``.txt`` / ``.csv`` format
========================================================

Loads pseudo-labels generated by a pretrained YOLO model
(e.g. ``model.predict(..., save_txt=True)``).

Supported input formats
-----------------------
* **YOLO txt (standard detection)**:
  one file per image, each line ``class cx cy w h [conf]``
  (normalised coordinates in [0, 1]).

* **YOLO txt (OBB)**:
  each line ``class x1 y1 x2 y2 x3 y3 x4 y4 [conf]``
  → auto-converted to axis-aligned ``cx cy w h``.

* **CSV**: one row per detection with configurable column names.

Output
------
A *dict* ``{ image_stem : {"classes": np.ndarray, "bboxes": np.ndarray} }``
that can be efficiently queried per batch during training.

A helper ``build_yolo_batch_from_pseudo`` converts the dict to the
flat-tensor format expected by ``v8DetectionLoss``.
"""

from __future__ import annotations

import csv
import logging
import os
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch

logger = logging.getLogger(__name__)


# ======================================================================
# Geometry helpers
# ======================================================================

def obb_to_aabb(coords: np.ndarray) -> np.ndarray:
    """
    Convert oriented bounding box (8 coords) to axis-aligned (cx, cy, w, h).

    Args:
        coords: ``[N, 8]`` array  ``x1 y1 x2 y2 x3 y3 x4 y4``

    Returns:
        ``[N, 4]`` array  ``cx cy w h``  (same coordinate space).
    """
    xs = coords[:, 0::2]  # columns 0, 2, 4, 6
    ys = coords[:, 1::2]  # columns 1, 3, 5, 7

    x_min = xs.min(axis=1)
    x_max = xs.max(axis=1)
    y_min = ys.min(axis=1)
    y_max = ys.max(axis=1)

    cx = (x_min + x_max) / 2
    cy = (y_min + y_max) / 2
    w = x_max - x_min
    h = y_max - y_min

    return np.stack([cx, cy, w, h], axis=1)


# ======================================================================
# Single-file parser
# ======================================================================

def parse_yolo_txt(
    txt_path: str,
    score_threshold: float = 0.0,
    convert_obb: bool = True,
) -> Tuple[np.ndarray, np.ndarray]:
    """
    Parse a YOLO-format ``.txt`` label file.

    The number of floats after the class index determines the format:

    ======  ============================
    count   interpretation
    ======  ============================
    4       standard  ``cx cy w h``
    5       standard + conf
    8       OBB  ``x1 y1 … x4 y4``
    9       OBB + conf
    ======  ============================

    Returns:
        classes:  ``[N]``    int64
        bboxes:   ``[N, 4]`` float32  ``cx cy w h``
    """
    text = Path(txt_path).read_text().strip()
    if not text:
        return np.zeros((0,), dtype=np.int64), np.zeros((0, 4), dtype=np.float32)

    classes_list: List[int] = []
    bboxes_list: List[List[float]] = []

    for line in text.split("\n"):
        parts = line.strip().split()
        if len(parts) < 5:
            continue

        cls = int(parts[0])
        vals = [float(x) for x in parts[1:]]

        if len(vals) == 4:
            bbox, conf = vals, 1.0
        elif len(vals) == 5:
            bbox, conf = vals[:4], vals[4]
        elif len(vals) == 8:
            if convert_obb:
                bbox = obb_to_aabb(np.array(vals).reshape(1, 8))[0].tolist()
            else:
                continue  # skip if OBB conversion disabled
            conf = 1.0
        elif len(vals) == 9:
            conf = vals[8]
            if convert_obb:
                bbox = obb_to_aabb(np.array(vals[:8]).reshape(1, 8))[0].tolist()
            else:
                continue
        else:
            continue

        if conf >= score_threshold:
            classes_list.append(cls)
            bboxes_list.append(bbox[:4])

    if not classes_list:
        return np.zeros((0,), dtype=np.int64), np.zeros((0, 4), dtype=np.float32)

    return (
        np.array(classes_list, dtype=np.int64),
        np.array(bboxes_list, dtype=np.float32),
    )


# ======================================================================
# Directory loader
# ======================================================================

def load_pseudo_labels_dir(
    label_dir: str,
    score_threshold: float = 0.5,
    convert_obb: bool = True,
) -> Dict[str, Dict[str, np.ndarray]]:
    """
    Load every ``.txt`` file in *label_dir* as pseudo-labels.

    Returns:
        ``{ image_stem: {"classes": ndarray[N], "bboxes": ndarray[N,4]} }``
    """
    label_dir = Path(label_dir)
    if not label_dir.exists():
        logger.warning(f"Pseudo-label dir does not exist: {label_dir}")
        return {}

    result: Dict[str, Dict[str, np.ndarray]] = {}
    for txt_file in sorted(label_dir.glob("*.txt")):
        stem = txt_file.stem
        classes, bboxes = parse_yolo_txt(
            str(txt_file), score_threshold, convert_obb,
        )
        if len(classes) > 0:
            result[stem] = {"classes": classes, "bboxes": bboxes}

    logger.info(
        f"Loaded pseudo-labels for {len(result)} images "
        f"from {label_dir}  (threshold={score_threshold})"
    )
    return result


# ======================================================================
# CSV loader
# ======================================================================

def load_pseudo_labels_csv(
    csv_path: str,
    image_col: str = "image",
    class_col: str = "class",
    bbox_cols: Sequence[str] = ("cx", "cy", "w", "h"),
    score_col: Optional[str] = "confidence",
    score_threshold: float = 0.5,
) -> Dict[str, Dict[str, np.ndarray]]:
    """
    Load pseudo-labels from a CSV file.

    Each row is one detection.  Rows are grouped by ``image_col`` (stem).

    Returns:
        Same format as :func:`load_pseudo_labels_dir`.
    """
    tmp: Dict[str, Dict[str, list]] = {}

    with open(csv_path, "r", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            if score_col and score_col in row:
                conf = float(row[score_col])
                if conf < score_threshold:
                    continue

            stem = Path(row[image_col]).stem
            cls = int(float(row[class_col]))
            bbox = [float(row[c]) for c in bbox_cols]

            if stem not in tmp:
                tmp[stem] = {"classes": [], "bboxes": []}
            tmp[stem]["classes"].append(cls)
            tmp[stem]["bboxes"].append(bbox)

    result = {
        stem: {
            "classes": np.array(d["classes"], dtype=np.int64),
            "bboxes": np.array(d["bboxes"], dtype=np.float32),
        }
        for stem, d in tmp.items()
    }
    logger.info(
        f"Loaded pseudo-labels for {len(result)} images from CSV {csv_path}"
    )
    return result


# ======================================================================
# Batch builder  (dict → YOLO flat-tensor format)
# ======================================================================

def build_yolo_batch_from_pseudo(
    pseudo_labels: Dict[str, Dict[str, np.ndarray]],
    image_stems: Sequence[str],
    device: torch.device,
) -> Optional[Dict[str, torch.Tensor]]:
    """
    Build a YOLO-compatible batch dict from pseudo-labels that match the
    current mini-batch images.

    Args:
        pseudo_labels: Output of ``load_pseudo_labels_dir`` / ``_csv``.
        image_stems:   List of stems for each image in the batch
                       (same order as the image tensor).
        device:        Target device.

    Returns:
        Dict with ``batch_idx``, ``cls``, ``bboxes`` — or *None* if no
        pseudo-labels match the current batch.
    """
    all_idx: List[int] = []
    all_cls: List[float] = []
    all_bboxes: List[List[float]] = []

    for i, stem in enumerate(image_stems):
        if stem not in pseudo_labels:
            continue
        pl = pseudo_labels[stem]
        n = len(pl["classes"])
        all_idx.extend([i] * n)
        all_cls.extend(pl["classes"].astype(float).tolist())
        all_bboxes.extend(pl["bboxes"].tolist())

    if not all_idx:
        return None

    return {
        "batch_idx": torch.tensor(all_idx, dtype=torch.float32, device=device),
        "cls": torch.tensor(all_cls, dtype=torch.float32, device=device).unsqueeze(-1),
        "bboxes": torch.tensor(all_bboxes, dtype=torch.float32, device=device),
    }


# ======================================================================
# MTKD targets → YOLO batch converter
# ======================================================================

def targets_to_yolo_batch(
    targets: Dict[str, torch.Tensor],
    device: torch.device,
) -> Dict[str, torch.Tensor]:
    """
    Convert the collated MTKD targets format::

        {"boxes": [B, max_obj, 4], "labels": [B, max_obj],
         "valid_mask": [B, max_obj]}

    to the flat YOLO batch format expected by ``v8DetectionLoss``::

        {"batch_idx": [N], "cls": [N, 1], "bboxes": [N, 4]}
    """
    boxes = targets["boxes"]    # [B, M, 4]
    labels = targets["labels"]  # [B, M]
    valid = targets.get("valid_mask")

    if valid is None:
        # Infer from non-zero boxes
        valid = boxes.sum(dim=-1) > 0  # [B, M]

    batch_idx_parts: List[torch.Tensor] = []
    cls_parts: List[torch.Tensor] = []
    bbox_parts: List[torch.Tensor] = []

    B = boxes.shape[0]
    for b in range(B):
        mask = valid[b]  # [M]
        n = mask.sum().item()
        if n == 0:
            continue
        batch_idx_parts.append(
            torch.full((n,), b, dtype=torch.float32, device=device)
        )
        cls_parts.append(labels[b][mask].float().unsqueeze(-1).to(device))
        bbox_parts.append(boxes[b][mask].float().to(device))

    if not batch_idx_parts:
        return {
            "batch_idx": torch.zeros(0, dtype=torch.float32, device=device),
            "cls": torch.zeros((0, 1), dtype=torch.float32, device=device),
            "bboxes": torch.zeros((0, 4), dtype=torch.float32, device=device),
        }

    return {
        "batch_idx": torch.cat(batch_idx_parts),
        "cls": torch.cat(cls_parts),
        "bboxes": torch.cat(bbox_parts),
    }
